#include<stdio.h>
main()
{
	printf("-----------------\n");
	printf("|\t\t|\n");
	printf("S\t\t|\n");
	printf("A\t\t|\n");
	printf("N\t\t|\n");
	printf("S\t\t|\n");
	printf("K\t\t|\n");
	printf("A\t\t|\n");
	printf("R\t\t|\n");
	printf("|\t\t|\n");
	printf("-----------------\n");
}
